#! /usr/bin/env bash
set -e

case "$BK_EXAMINATION" in

	StateSpace)
		echo "DO_NOT_COMPETE"
		;;

	UpperBounds)
		echo "DO_NOT_COMPETE"
		;;

	Reachability*)
		echo "DO_NOT_COMPETE"
		;;

	LTL*)
		echo "DO_NOT_COMPETE"
		;;

	CTL*)
		echo "DO_NOT_COMPETE"
		;;

	*)
		echo "$0: Wrong invocation:" >> $BK_LOG_FILE
		exit 1
		;;
esac
