#! /usr/bin/env bash
set -e

case "$BK_EXAMINATION" in

	StateSpace)
		if [[ `grep TRUE iscolored` ]]
		then
		  echo "DO_NOT_COMPETE"
		fi
	  MODEL_NAME=$(echo "$BK_INPUT" | cut -d '-' -f 1)
	  MODEL_TYPE=$(echo "$BK_INPUT "| cut -d '-' -f 2)
	  MODEL_INST=$(echo "$BK_INPUT" | cut -d '-' -f 3)
	  echo "======================================================"
	  echo "========== this is Smart for the MCC'2017 ============"
	  echo "======================================================"
	  echo "Runing $MODEL_NAME ($MODEL_TYPE), instance $MODEL_INST"
	  echo
    java -classpath /usr/share/smart/ cleanparse/CleanParse model.pnml
	  smart model.sm
		;;

	UpperBounds)
		echo "DO_NOT_COMPETE"
		;;

	Reachability*)
		echo "DO_NOT_COMPETE"
		;;

	LTL*)
		echo "DO_NOT_COMPETE"
		;;

	CTL*)
		echo "DO_NOT_COMPETE"
		;;

	*)
		echo "$0: Wrong invocation:" >> $BK_LOG_FILE
		exit 1
		;;
esac
