sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - shellcheck
language: python
python:
  - "3.6"
  # - "nightly"
install:
  - pip install -r requirements.txt
script:
  - shellcheck build-images install prepare
  - pycodestyle mcc4mcc/*.py
  - pylint mcc4mcc/*.py
notifications:
  email:
    - alban.linard@gmail.com
  on_success: change
  on_failure: change
