#! /usr/bin/env bash

set -e

docker login

for tool in *
do
  if [ -d "${tool}" ] && [ -f "${tool}/Dockerfile" ] && [ ! -f "${tool}/disable" ]
  then
    echo "Building docker image for ${tool}."
    ( cd "${tool}"
      if [ -x prepare ]
      then
        ./prepare
      fi
      docker build \
             --tag="mccpetrinets/${tool}" \
             --force-rm \
             --squash \
             .
      docker push "mccpetrinets/${tool}"
    )
  fi
done
