#! /usr/bin/env bash

docker login \
  -u "${DOCKER_USERNAME}" \
  -p "${DOCKER_PASSWORD}"

# Install docker images:
for tool in gspn \
            lola \
            marcie \
            ltsmin \
            itstools \
            pnmc \
            smart \
            spot \
            stratagem \
            tapaal \
            tina
do
  if [ -d "${tool}" ] && [ -f "${tool}/Dockerfile" ] && [ ! -f "${tool}/disable" ]
  then
    ( cd "${tool}"
      if [ -x prepare ]
      then
        ./prepare
      fi
      docker build \
             --tag="mccpetrinets/${tool}" \
             --force-rm \
             --squash \
             .
      docker push "mccpetrinets/${tool}"
    ) || exit 1
  fi
done
