#! /usr/bin/env bash

for tool in *
do
  if [ -d "${tool}" ] && [ -f "${tool}/Dockerfile" ]
  then
    echo "${tool}"
    sem --jobs -4 "cd ${tool}; \
      docker build \
             --tag=saucisson/${tool} \
             --force-rm \
             --squash \
             ."
  fi
done
sem --wait
