#! /usr/bin/env bash

set -e

read -r    -p "Docker username? " docker_username
read -r -s -p "Docker password? " docker_password

source ./prepare
source ./build-images

echo "Creating the virtual machine for the model checking contest."

# Clean:
VBoxManage controlvm "mcc4mcc" \
  poweroff \
  || true
VBoxManage modifyvm "mcc4mcc" \
  --hdb "none" \
  || true
VBoxManage unregistervm "mcc4mcc" \
  --delete \
  || true
cp "ToolSubmissionKit/mcc2018.vmdk" \
   "mcc4mcc.vmdk"

# Launch the virtual machine:
VBoxManage createvm \
  --name "mcc4mcc" \
  --ostype "Debian_64" \
  --register
VBoxManage storagectl "mcc4mcc" \
  --name "IDE Controller" \
  --add "ide" \
  --bootable "on"
VBoxManage modifyvm "mcc4mcc" \
  --description "Model Checker Collection for the Model Checking Contest" \
  --memory 8192 \
  --cpus 4 \
  --hda "mcc4mcc.vmdk" \
  --hdb "$(pwd)/ToolSubmissionKit/mcc2018-input.vmdk" \
  --natpf1 ssh,tcp,,2222,,22
VBoxManage startvm "mcc4mcc" \
  --type "headless"

# Install dependencies:
ssh \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "ToolSubmissionKit/bk-private_key" \
  -p 2222 \
  root@localhost \
  'bash -s' <<'EOS'
set -e
apt-get update  --yes
apt-get upgrade --yes
apt-get install --yes \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg \
  | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"
apt-get update  --yes
apt-get install --yes \
  docker-ce \
  python3-pip
adduser mcc docker
pip3 install numpy
pip3 install scikit-learn
pip3 install xmltodict
mkdir -p     /usr/local/share/mcc4mcc
chown -R mcc /usr/local/share/mcc4mcc
EOS

# Install docker images:
docker images mccpetrinets/*:latest --format "{{.Repository}}:{{.Tag}}" \
  > "images.txt"

# Install mcc4mcc:
rm -rf ./*/from-vm
scp \
  -r \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "ToolSubmissionKit/bk-private_key" \
  -P 2222 \
  . \
  root@localhost:/usr/local/share/mcc4mcc/
scp \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "ToolSubmissionKit/bk-private_key" \
  -P 2222 \
  BenchKit_head.sh \
  root@localhost:BenchKit/

# shellcheck disable=SC2029
ssh \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "ToolSubmissionKit/bk-private_key" \
  -p 2222 \
  root@localhost \
  "DOCKER_USERNAME=${docker_username} \
   DOCKER_PASSWORD=${docker_password} \
   bash -s" <<"EOS"
set -e
pip install /usr/local/share/mcc4mcc
docker login \
  --username="${DOCKER_USERNAME}" \
  --password="${DOCKER_PASSWORD}"
for image in $(cat /usr/local/share/mcc4mcc/images.txt)
do
  docker pull ${image}
done
chown -R mcc /usr/local/share/mcc4mcc
EOS

# Stop:
ssh \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "ToolSubmissionKit/bk-private_key" \
  -p 2222 \
  root@localhost \
  'bash -s' <<"EOS"
set -e
apt-get install --yes \
  zerofree
apt-get autoremove --yes
apt-get clean
rm -rf /var/lib/apt/lists/*
sync
# mount -n -o remount,ro /dev/sda1 /
# zerofree /dev/sda1
EOS
VBoxManage controlvm "mcc4mcc" \
  poweroff
rm -f "mcc4mcc.vdi"
rm -f "mcc4mcc-2018.vmdk"
VBoxManage clonemedium \
  --format=VDI \
  "mcc4mcc.vmdk" \
  "mcc4mcc.vdi"
VboxManage modifymedium  \
  --compact \
  "mcc4mcc.vdi"
VBoxManage clonemedium \
  --format=VMDK \
  "mcc4mcc.vdi" \
  "mcc4mcc-2018.vmdk"
rm -f "mcc4mcc.vdi"

echo "The virtual machine has been generated in mcc4mcc-2018.vmdk."
