#! /usr/bin/env bash
set -e

java -Dosgi.requiredJavaVersion=1.6 \
     -Xss8m \
     -Xms40m \
     -Xmx8192m \
     -Declipse.pde.launch=true \
     -Dfile.encoding=UTF-8 \
     -classpath $(find "/usr/share/itscl" -name "org.eclipse.equinox.launcher*.jar") \
     org.eclipse.equinox.launcher.Main \
     -application fr.lip6.move.gal.application.pnmcc \
     -data "/usr/share/itscl/eclipse/workspace" \
     -os linux \
     -ws gtk \
     -arch x86_64 \
     -nl en_US \
     -consoleLog \
     -z3path     "/usr/bin/z3" \
     -yices2path "/usr/bin/yices" \
     -ltsminpath "/usr/bin" \
     -smt \
     -its \
     -pnfolder "${PWD}" \
     -examination "${BK_EXAMINATION}"
