#! /usr/bin/env bash

java -Dosgi.requiredJavaVersion=1.6 \
     -Xss8m \
     -Xms40m \
     -Xmx8192m \
     -Declipse.pde.launch=true \
     -Dfile.encoding=UTF-8 \
     -classpath /usr/share/itscl/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar \
     org.eclipse.equinox.launcher.Main \
     -application fr.lip6.move.gal.application.pnmcc \
     -data /usr/share/itscl/workspace \
     -os linux \
     -ws gtk \
     -arch x86_64 \
     -nl en_US \
     -consoleLog \
     -z3path /usr/local/bin/z3 \
     -yices2path /usr/local/bin/yices \
     -ltsminpath /usr/local/bin \
     -smt \
     -its \
     -pnfolder "$(pwd)" \
     -examination "${BK_EXAMINATION}"
