#! /usr/bin/env bash
set -e

export GSPN_PATH="/usr/share/GreatSPN"
export PATH="${GSPN_PATH}/bin:${GSPN_PATH}/scripts:${PATH}"

case "$BK_EXAMINATION" in

	StateSpace|UpperBounds|Reachability*|CTL*)
		true
		;;

	LTL*)
		echo 'DO_NOT_COMPETE'
		exit 0
		;;

	*)
		echo "$0: Wrong invocation:"
		echo 'DO_NOT_COMPETE'
		exit 0
		#exit 1
		;;
esac


varord="META"
meddlyCache="67108864"

ulimit -s 32768
if [[ `cat iscolored` == "TRUE" ]]
then
    colored="1"
    unfoldingParams="-unfolding-map model.unfmap"
    #echo "Running on a Colored net"
else
    colored=""
    unfoldingParams=""
    #echo "Running on a PT net"
fi


if [[ ! -f model.def ]]
then
    timeout 300s java -mx2000m \
			-cp "${GSPN_PATH}/bin/Editor.jar":"${GSPN_PATH}/bin/lib/antlr-runtime-4.2.1.jar" \
			editor.UnfoldPNML2NetDefCommandLineTool model -name-map
    if [[ $? -ne "0" ]]
    then
        echo 'CANNOT_COMPUTE'
        exit 0
    fi
    #echo "Computing bounds, with a timeout of 30s"
    timeout 30s struct model -only-bnd -detect-exp \
			|| rm -f model.bnd model.pin
fi

if [[ -f model.bnd ]]
then
    #echo 'Bounds computed'
    boundParam="-guess-load-from-file"
else
    #echo "Bounds not computed"
    boundParam="-guess-max0-exp"
fi

case $BK_EXAMINATION in
    StateSpace)
        #echo 'Computing state space'
        MCC=1 RGMEDD2 model -$varord -event-nsf -h $meddlyCache $boundParam
        ;;
    UpperBounds|Reachability*|CTL*)
        xmlFile="$BK_EXAMINATION.xml"
        ctlFile="$BK_EXAMINATION.ctl"
        if [[ ! -f $ctlFile ]]
        then
            #echo "Converting $BK_EXAMINATION formulas"
            java -jar "${GSPN_PATH}/bin/MccCtlConv.jar" $xmlFile -name-map model.id2name $unfoldingParams > $ctlFile
        #else
        #    echo "$BK_EXAMINATION formulas already converted. Using them"
        fi
        #echo "Evaluating $BK_EXAMINATION formulas"
        MCC=1 RGMEDD2 model -$varord -mono-nsf -h $meddlyCache $boundParam -C -f $ctlFile
        ;;
    *)
        echo 'DO_NOT_COMPETE'
        ;;
esac
