#! /usr/bin/env bash

set -e

name="gspn2017"
port=${1:-2222}

# Clean:
VBoxManage controlvm "${name}" \
  poweroff \
  || true
VBoxManage unregistervm "${name}" \
  --delete \
  || true

# Download virtual machine:
if [ ! -f "${name}.vmdk.bz2" ]
then
  curl -L "https://mcc.lip6.fr/2017/archives/${name}.vmdk.bz2" \
       -z "${name}.vmdk.bz2" \
       -o "${name}.vmdk.bz2"
fi

# Extract image:
if [ ! -f "${name}.vmdk" ]
then
  tar xf "${name}.vmdk.bz2"
fi

# Launch the virtual machine:
VBoxManage createvm \
  --name "${name}" \
  --ostype "Debian_64" \
  --register
VBoxManage storagectl "${name}" \
  --name "IDE Controller" \
  --add "ide" \
  --bootable "on"
VBoxManage modifyvm "${name}" \
  --description "${name} for mcc4mcc" \
  --memory 8192 \
  --cpus 4 \
  --hda "${name}.vmdk" \
  --natpf1 ssh,tcp,,${port},,22
VBoxManage startvm "${name}" \
  --type "headless"

# Copy files from the virtual machine:
rm -rf from-vm/
mkdir -p from-vm/
scp \
  -r \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "../ToolSubmissionKit/bk-private_key" \
  -P "${port}" \
  mcc@localhost:/usr/local \
  from-vm/local/
scp \
  -r \
  -o "UserKnownHostsFile=/dev/null" \
  -o "StrictHostKeyChecking=no" \
  -i "../ToolSubmissionKit/bk-private_key" \
  -P "${port}" \
  mcc@localhost:BenchKit/bin/MccCtlConv.jar \
  from-vm/

# Clean:
VBoxManage controlvm "${name}" \
  poweroff
VBoxManage unregistervm "${name}" \
  --delete
