#! /usr/bin/env bash
set -e

MARCIE_CONFIG="--memory=6"
TIMEOUT="timeout --kill-after=10s --signal=SIGINT 1m"
MARCIE="marcie"

case "$BK_EXAMINATION" in

  StateSpace)
    echo "${TIMEOUT} for testing only"
    ${MARCIE} --net-file=model.pnml ${MARCIE_CONFIG}
  ;;

  UpperBounds)
    echo "${TIMEOUT} for testing only"
    ${MARCIE} --net-file=model.pnml --mcc-file=${BK_EXAMINATION}.xml ${MARCIE_CONFIG}
  ;;

  Reachability*)
    echo "${TIMEOUT} for testing only"
    ${MARCIE} --net-file=model.pnml --mcc-file=${BK_EXAMINATION}.xml ${MARCIE_CONFIG}
  ;;

  CTL*)
    echo "${TIMEOUT} for testing only"
    ${MARCIE} --net-file=model.pnml --mcc-file=${BK_EXAMINATION}.xml ${MARCIE_CONFIG}
  ;;

  LTL*)
    echo "DO_NOT_COMPETE"
  ;;

  *)
    echo "$0: Wrong invocation:" >> $BK_LOG_FILE
    exit 1
    ;;
esac
